### ISSUE TITLE
glance returns incorrect R² values for a linear model with observation weights

### ISSUE THREAD

**Issue by dhimmel** [dgrtwo/broom#113]
Running `broom::glance` gives on an `lm` output gives me different R-squared values than `summary`. Specifically, see cells 9 and 11 in [the this notebook](https://github.com/dhimmel/elevcan/blob/67a33acf794f0609f9dd15ff4555a6674c9edcd8/manual/tutorial/tutorial.ipynb "R notebook showing broom bug").

My guess is that broom is not properly handling observation weights. [Here is a gist](https://gist.github.com/dhimmel/588d64a73fa4fef02c8f "Computing the R-squared of a linear regression model with weighted observations in R") I made with different methods for calculating weighted R², in case it's helpful.

**Comment by dgrtwo** [comment]
I'm afraid I can't see the difference myself; line 9 (summary) has:

    Multiple R-squared:  0.7024,	Adjusted R-squared:  0.6964 

And line 11 has:

    	r.squared	adj.r.squared	sigma...
    1	0.7024248	0.6964011	131.2217...

That is, line 9 is just line 11 rounded to four decimal places. Could you point out what I am missing?

**Comment by dhimmel** [comment]
@dgrtwo I'm afraid I am going crazy (;

Lesson: recheck your notebook output after doing a restart and run all!
