### ISSUE TITLE
Problem with S3 method for tidy.dgCMatrix

### ISSUE THREAD

**Issue by lmullen** [dgrtwo/broom#119]
I'm trying to use the tidier for objects in the Matrix package. The methods themselves work when called directly, but they are not found when called as `tidy()`. A reproducible example:

```
library(Matrix)
library(broom)

m <- rsparsematrix(6, 8, density = 0.3)
class(m)
#> [1] "dgCMatrix"
#> attr(,"package")
#> [1] "Matrix"
tidy(m)
```

This produces an error message:

```
Error in as.data.frame.default(x) : 
  cannot coerce class "structure("dgCMatrix", package = "Matrix")" to a data.frame
In addition: Warning message:
In tidy.default(m) :
  No method for tidying an S3 object of class dgCMatrix , using as.data.frame
```

But 

```
broom:::tidy.dgCMatrix(m)
```

produces a data frame of rows, columns, and values as expected.

I'm using broom 0.4 installed from GitHub:

```
 broom      * 0.4.0   2016-04-02 Github (dgrtwo/broom@14e70a6)
```

**Comment by dgrtwo** [comment]
Thanks! Mid-hackathon git mistakes :)

**Comment by lmullen** [comment]
:rocket: Works perfectly. Thanks. Didn't realize this was a new addition to broom.
