### ISSUE TITLE
lmodel2

### ISSUE THREAD

**Issue by jjvenky** [dgrtwo/broom#129]
The first example in the broom README is based on the regular model I linear model lm() function. Sometimes model II linear regressions are needed and the lmodel2 package provides this: [https://cran.r-project.org/web/packages/lmodel2/index.html]. Since the outputs of lmodel2() are a little different than lm() broom::tidy doesn't quite like it. Perhaps this is an enhancement for broom or for purrr: [https://github.com/hadley/purrr].

**Comment by dgrtwo** [comment]
Thanks for the idea! This should have basically all the output you'd want

**Comment by jjvenky** [comment]
Fantastic! Thanks.
