### ISSUE TITLE
poLCA

### ISSUE THREAD

**Issue by Daibhaidh** [dgrtwo/broom#130]
I'm fairly new to R but am hoping to use the poLCA package to run multiple Latent Class Analyses on a large health dataset. 
I luckily made it to Hadley's [talk in Edinburgh](https://www.youtube.com/watch?v=rz3_FDVt9eg) a couple of weeks ago and would love to incorporate the broom package in my analysis as I will be running lots of different models requiring comparison of BIC stats.  
Is there any likelihood of poLCA being added to broom anytime?

**Comment by dgrtwo** [comment]
Done! Please try out these new tidiers (see `?poLCA_tidiers` for help) and let me know what you think. I can always adapt or adjust the outputs.

**Comment by Daibhaidh** [comment]
Awesome! Thanks a lot.

I’ll let you know how I get on!

David
