### ISSUE TITLE
Add tidier for lsmeans objects

### ISSUE THREAD

**Issue by thomasjwood** [dgrtwo/broom#139]
Fantastic package--is there any plan to add a tidier for `lsmeans` objects?

**Comment by ashander** [comment]
Great idea. Game for a pull request!?

**Comment by dgrtwo** [comment]
Now added: please check out `?lsmeans_tidiers` and try it out. Let us know if it doesn't cover what you'd expect!

**Comment by thomasjwood** [comment]
Fantastic--amazed you got to this so quickly. thanks!
