### ISSUE TITLE
Is this the package for a trimming function to sit in?

### ISSUE THREAD

**Issue by Mullefa** [dgrtwo/broom#22]
There's a good [article](http://blog.yhathq.com/posts/reducing-your-r-memory-footprint-by-7000x.html) on yhat: _Reducing your R memory footprint by 7000x_. 

Do you think this is the package for a generic trimming function to sit in? If so, I'd be happy to help.

**Comment by dgrtwo** [comment]
This is a *brilliant* idea for a package! I don't think it fits in broom for a few reasons:

- All broom tidiers return data frames, while this would be returning objects of the same format as the original ("messy" objects)
- The output of a trimming function would not necessarily be compatible with broom tidiers (in particular, augment relies on the object keeping the data)

Perhaps you should start a new package, possibly called `trimmr`? I'd be very interested in contributing
