### ISSUE TITLE
Error in eval(expr, envir, enclos) : object 'group1' not found

### ISSUE THREAD

**Issue by mostly-harmless** [dgrtwo/broom#24]
FYI When using tidy with pairwise.t.test the following code gives an error

    library(broom)
    dat <- mtcars
    dat$vs <- as.factor(mtcars$vs)
    res <- pairwise.t.test(dat[,"mpg"], dat[,"vs"])
    tidy(res)

    Error in eval(expr, envir, enclos) : object 'group1' not found

Recoding the levels seems to 'fix' the issue. 

    vs <- as.character(mtcars$vs)
    vs[vs == 1] <- "manual"
    vs[vs == 0] <- "automatic"
    dat$vs2 <- as.factor(vs)
    res <- pair

Really like Broom. Thanks!

**Comment by dgrtwo** [comment]
Thanks!!
