### ISSUE TITLE
lapplying tidy() to aovlist-objects

### ISSUE THREAD

**Issue by crsh** [dgrtwo/broom#26]
I have had some trouble tidying `avolist` objects. When performing a repeated measures analysis of variance the optput object is usually a list of `aov` objects for the different error strata.

    datafilename <- "http://personality-project.org/r/datasets/R.appendix5.data"
    aov_example <- read.table(datafilename, header = T)
    aov_example <- aov(Recall ~ (Task*Valence*Gender*Dosage) + Error(Subject/(Task*Valence)) +(Gender*Dosage), aov_example)
    class(aov_example)

> [1] "aovlist" "listof"

(example stolen from http://personality-project.org/r/#anova)

To-date, it is not possible to tidy these objects directly because `fix_data_frame()` doesn't take lists.

    library("broom")
    tidy(aov_example)

> Error in as.data.frame.default(x) : 
>  cannot coerce class "c("aovlist", "listof")" to a data.frame

So I tried to use `lapply()`, but this throws an error:

    lapply(aov_example, tidy)

> Error in \`colnames<-\`(\`\*tmp\*\`, value = c("df", "sumsq", "meansq", "statistic",  : 
>  Attribute 'names' [5] must be of same length as vector [3]

Is there an easy fix for this? It would be convenient if `tidy()` accepted `aovlist`-objects.

**Comment by dgrtwo** [comment]
Good idea, thanks! tidy.aovlist has been added.

**Comment by crsh** [comment]
Thanks for your prompt reply and fix!

Unfortunately, I just installed `broom` from this repository to test the new method and it seems that `tidy.aovlist` currently drops the first error stratum:

    devtools::install_github("dgrtwo/broom")
    library("broom")
    tidy(aov_example)

I had a look at the method and I think it's due to this line:

    ret <- plyr::ldply(x[-1], tidy, .id = "stratum")

I'm not sure why the first element of `x` is removed at this point. But omitting it returns a complete object:

    tidy.aovlist <- function(x, ...) {
        # must filter out Intercept stratum since it has no dimensions
        if (names(x)[1L] == "(Intercept)") {
        x <- x[-1L]
      }
  
      ret <- plyr::ldply(x, tidy, .id = "stratum")
      # get rid of leading and training whitespace in term and stratum columns
      ret <- ret %>% mutate(term = stringr::str_trim(term),
                        stratum = stringr::str_trim(stratum))
      ret
    }
    
    tidy(aov_example)

**Comment by dgrtwo** [comment]
Whoops- I had forgotten that I'd already dropped the `"(Intercept)"` stratum in the previous if statement. Fixed now!
