### ISSUE TITLE
Enhance documentation of tidy

### ISSUE THREAD

**Issue by simonthelwall** [dgrtwo/broom#29]
Would it be possible to enhance the documentation of tidy? The current documentation gives 

> Usage
> tidy(x, ...)
> 
> Arguments
> x	An object to be converted into a tidy data.frame
> ...	extra arguments

What the extra arguments might be aren't described anywhere I can find them. I know of conf.int and exponentiate from issue #5, are there others?

**Comment by dgrtwo** [comment]
`tidy` is an S3 generic that describes a whole class of methods, meaning the definition of the extra arguments is intentionally ambiguous. There are many other arguments that can be used by `tidy`, but it depends entirely on the specific method that is used. The documentation for each of those tidiers lives in `tidy.<model_name>`, such as:

    ?tidy.lm  # this reaches, e.g., the docs for conf.level and exponentiate
    ?tidy.nls
    ?tidy.survreg

They can also be reached with:

    ?lm_tidiers
    ?nls_tidiers
    ?survreg_tidiers
