### ISSUE TITLE
dplyr, glance and p.adjust

### ISSUE THREAD

**Issue by rghan** [dgrtwo/broom#33]
I was performing some regressions similar to the below example, when I noticed that `p.adjust` does not seem to do anything to p.values after a `glance()` has been called.

```
data(mtcars)
mtcars %>% 
    group_by(gear) %>% 
    do(mod = lm(mpg~wt, data=.)) %>% 
    glance(mod) %>% 
    mutate(fdr=p.adjust(p.value, method="fdr")) %>% 
    select(p.value, fdr)

$ Source: local data frame [3 x 3]
$ Groups: gear
$
$ gear      p.value          fdr
$ 1    3 0.0006048395 0.0006048395
$ 2    4 0.0010104804 0.0010104804
$ 3    5 0.0012815520 0.0012815520
```
Am I missing something here?

```
$ version  R version 3.1.2 (2014-10-31)
$ system   x86_64, darwin13.4.0       
$ broom           0.3.6       2015-02-18 CRAN (R 3.1.2)
$ dplyr           0.4.1       2015-01-14 CRAN (R 3.1.2)
```

**Comment by dgrtwo** [comment]
This is because they are still grouped by `gear` for the mutate operation: add an `ungroup()` before the mutate.

I'll probably change this behavior so it is returned ungrouped.

**Comment by rghan** [comment]
Ah, that makes sense. Thanks for the quick reply!
