### ISSUE TITLE
What about model fits?

### ISSUE THREAD

**Issue by helix123** [dgrtwo/broom#41]
In my pre-broom code, I just plugged the model fits (like R^2 of (p)lm models) in a separate column with the same value in each line, ie for each coefficient as it is just one value for the whole model. Sure, this is not tidy data.

Would be nice to have a command to extract all model fit indicators in a tidy format (one column per indicator and just one line). For comparing different models this would be really handy as one can just rbind those tidy outputs. This idea could be related to the list discussion in #40. What do you think?

**Comment by dgrtwo** [comment]
Isn't that just the `glance` method? e.g.

    > glance(lm(mpg ~ wt, mtcars))
      r.squared adj.r.squared    sigma statistic      p.value df    logLik      AIC      BIC deviance df.residual
    1 0.7528328     0.7445939 3.045882  91.37533 1.293959e-10  2 -80.01471 166.0294 170.4266 278.3219          30

**Comment by helix123** [comment]
Umh, yes thank you! Sorry, have not seen that (just did ?tidy...).
Putting tidy(lm(.)) and glance(lm(.)) in a list to store and compare differnt model-data combinations is now an easy task for me!
