### ISSUE TITLE
augment for loess object

### ISSUE THREAD

**Issue by joranE** [dgrtwo/broom#43]
I was going to dip my toe gently into exploring broom by trying to add an `augment` method for `loess` objects, but I'm not sure how you'd prefer that to be done. 

Initially, it seemed like a simple matter of adding an S3 method `augment.loess` that just called `augment_columns`, along the lines of `augment.lm`. But in keeping with base R's sometimes inconsistent argument naming `predict.loess` uses the argument `se` rather than `se.fit`.

It's easy enough to write a completely self-contained `augment.loess` function, but it wasn't clear to me looking at the rest of the package whether you preferred that type of approach, or whether you prefer code that's a bit more centralized.

**Comment by dgrtwo** [comment]
Great idea and good question! Luckily there's an easy way you can still use `augment_columns`, which is to pass `se = TRUE` to the `...`, which gets passed on to `predict`. For instance:

    x <- loess(mpg ~ wt, mtcars)
    augment_columns(x, model.frame(x), se.fit = FALSE, se = TRUE)

(Note that the `se.fit = FALSE` argument is necessary to prevent partial argument matching, which would match `se` to `se.fit`).

**Comment by joranE** [comment]
I took a stab at it, apologies if I messed up anything git/github related.
