### ISSUE TITLE
tidy method for anova misses a column name

### ISSUE THREAD

**Issue by agoldst** [dgrtwo/broom#62]
Applying `tidy` to the results of `anova` on more than one model yields a data frame where all the column names are off by one (and the last column has name `NA`):

```r
m1 <- lm(mpg ~ wt + qsec + disp, mtcars)
m2 <- lm(mpg ~ wt, mtcars)
a <- anova(m1, m2)
```

Now `print(a)` gives

````
Analysis of Variance Table

Model 1: mpg ~ wt + qsec + disp
Model 2: mpg ~ wt
  Res.Df    RSS Df Sum of Sq      F   Pr(>F)   
1     28 195.46                                
2     30 278.32 -2   -82.859 5.9348 0.007099 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
````

but `tidy(a)` gives

````
  df    sumsq meansq statistic  p.value          NA
1 28 195.4626     NA        NA       NA          NA
2 30 278.3219     -2 -82.85933 5.934796 0.007099496
````

It looks like `tidy.anova` assumes `a` has five columns, but it has six; the method misses the third column of `a` (the `Df` column). Apologies for not putting together a pull request, and thanks for this fantastic package.

**Comment by nutterb** [comment]
This is another type of ANOVA, and is really more of a likelihood ratio test than an analysis of variance.  

But this can be resolved as easily as adding another `else if{}`

```r
else if (identical(colnames(x), c("Res.Df", "RSS", "Df", "Sum of Sq", "F", "Pr(>F)"))){
    # x is anova(m1, m2)
    nn <- c("res.df", "rss", "df", "sumsq", "statistic", "p.value")
  }
```
