### ISSUE TITLE
 could not find function "is"

### ISSUE THREAD

**Issue by hadley** [dgrtwo/broom#67]
Deep in the internals of building the ggplot2 book, I get:

```R
Error in tidy.lm(.[[object]][[1]], ...) : could not find function "is"
Calls: render_chapter ... do_ -> do_.grouped_df -> eval -> eval -> func -> tidy.lm
Execution halted
```

Any ideas?  It's from a line like `coefs <- models %>% tidy(mod)` where `mod` is a linear model.

**Comment by dgrtwo** [comment]
Must be the `is(` in [this line](https://github.com/dgrtwo/broom/blob/master/R/lm_tidiers.R#L140):

    nn <- c("estimate", "std.error", "statistic", "p.value")
    if (is(co, "listof")) {
        # multiple response variables
        ret <- plyr::ldply(co, fix_data_frame, nn[1:ncol(co[[1]])],
                           .id = "response")
        ret$response <- stringr::str_replace(ret$response, "Response ", "")
    } 

I thought the `is` function comes with the `methods` package, which I thought has been built-into R for a while. What version of R? (or full `sessionInfo()`?) I could change it to `"listof" %in% class(co)`, of course.

**Comment by nutterb** [comment]
Starting in June, CRAN requires that everything not in `base` has to be imported. My merge request #64 takes care of most of them, but the `is` methods gave me a weird message that I wasn't able to properly investigate. My guess is that if we can resolve the CRAN check messages, hadley's problems will resolve. 

If you run check on R-developing with --as-cran, it will tell you exactly where the two instances of `is` occur.

**Comment by hadley** [comment]
That should be inherits, not is, anyway. 

Methods is tricky because it's not attached when run from Rscript.

**Comment by dgrtwo** [comment]
Ah, that explains it. Easy fix, thanks

**Comment by JonN17** [comment]
I just got this error.  How do you implement the fix?
