### ISSUE TITLE
Adding key information to augment for future joins

### ISSUE THREAD

**Issue by jmh530** [dgrtwo/broom#91]
I just tried out broom and I'm really liking it. However, I am seeing an issue. It might be that there is an option that I'm not seeing to fix it.

The code below creates a `df1` data frame, runs some regressions by group, and then creates an `output` data frame that contains the residuals and such. What I want to do is merge the `output` data frame with the original `df1` data frame. However, the `output` data frame doesn't have the id column to join on. It only has the group column.

    library(dplyr)
    library(broom)

    N <- 1000
    N_group <- 100

    set.seed(32)

    df1 <- data.frame(id=1:1000, 
    				  group=sample.int(N_group, size = N, replace = TRUE),
    				  x=rnorm(N))
    df1$y <- 2*df1$x + rnorm(N)

    lm_df1 <- df1 %>%
    			group_by(group) %>%
    			do(model = lm(y ~ x, data = .))
			
    output <- augment(lm_df1, model)

The thing that would put me most at ease for avoiding any errors is to be able to also get the id column in to the `output` data frame somehow. Ideally, I would want to have the last line instead as

    output <-  augment(lm_df1, model, key=df1$id)

(where output would have an additional field named id, matching up with what is in df1, not a field named key) and then I can just create the merged data frame as

    df2 <- inner_join(df1, output, by=id)

Nevertheless, I did think of some potential workarounds. I'm just worried that these might have some errors. 

For instance, one potential quick fix is using dplyr to arrange(group, id) before running augment, but that is a bit risky...maybe sufficient for a simple fix but not a permanent solution. 

Another option is to do the join using as much information as possible from output. I put some code below illustrating this. The requirement would need to be that group, y, and x are sufficient to join on. I don't think this is an issue for my actual data set (so that's what I'll go with for now), but I can imagine that someone else might have an issue with this. 

    output <- lm_df1 %>%
    			augment(model) %>%
    			select(group, y, x, .resid)

    df2 <- df1 %>%
    			inner_join(output, by=c("group", "y", "x"))

**Comment by KaBach** [comment]
Hi

I am actually facing exactly the same issue at the moment. I am currently using the 'quick fix' you mentioned, so arrange both data frames and then cbind. I have doublechecked everything a couple of times and I think it is fine this way. But I do feel very uncomfortable with that solution to be honest. Unfortunately, the information in group, x and y is for me not sufficient for joining. 

So having a key variable in augment would be awesome!

**Comment by dgrtwo** [comment]
Sorry that I missed this at the time. This has an easy solution: `augment` takes a second, `data` argument (for many objects in fact), that has it do the merging. When this is done in groups, the pattern looks like:

```
lm_df1 <- df1 %>%
  group_by(group) %>%
  do(model = lm(y ~ x, data = .), d = (.))

output <- augment(lm_df1, model, data = d)
output
```

Notice that we saved the data as a second list column, then passed the name of that column to the `data = ` argument. This should be easier than either cbinding or inner joining
