### ISSUE TITLE
tidy.summaryDefault with NAs in data

### ISSUE THREAD

**Issue by bbolker** [dgrtwo/broom#92]
As discussed [here](http://stackoverflow.com/questions/33881557/broomtidy-with-do-in-a-dplyr-workflow-fails-with-a-summarydefault-object/33882837#33882837), `tidy.summaryDefault` assumes that `summary()` results have six elements, not seven (as will be the case if the data contain `NA` values).

The example given there:

```
df <- data.frame(group = c(rep('M', 6), 'F', 'F', 'M', 'M', 'F', 'F'),
                 val = c(6, 5, NA, NA, 6, 13, NA, 8, 10, 7, 14, 6))
library("plyr"); library("broom")
df %>% group_by(group) %>% do(tidy(summary(.$val)))
# Error: corrupt data frame at index 1
```

This should be pretty easy to fix ...

**Comment by dgrtwo** [comment]
Fixed by #79
